FROM runmymind/docker-android-sdk:ubuntu-standalone 
#
MAINTAINER Milan Enev <milan@mreji.net>
#
ENV NODE_VERSION "8.11.1"
ADD ./scripts/install_packages.sh /tmp/
RUN /bin/bash /tmp/install_packages.sh
#EXPOSE 9000
