version: "3"
services:
  www:
    container_name: sf4_ub18
    build: './'
    networks:
      - frontend
    ports:
      - "8080:8080"
    environment:
        APP_ENV: prod
        DATABASE_URL: "mysql://db_user:db_password@127.0.0.1:3306/db_name"
networks:
  frontend:
